// The AI diagnosis card.
//
// Every claim carries a "Why?" control that opens the evidence drawer, and the
// card always states whether the diagnosis came from the model or the
// deterministic rules engine.

import { ToneGlyph, SkeletonLine } from './primitives'
import type { CausalClaim, Diagnosis, TracedTransaction } from '../types'
import type { EvidenceRequest } from './EvidenceDrawer'

function WhyButton({ onClick, label }: { onClick: () => void; label: string }) {
  return (
    <button type="button" onClick={onClick} className="why-btn" aria-label={label}>
      <svg className="h-3 w-3" viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="2" />
        <path d="M12 11v5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <circle cx="12" cy="7.75" r="1.15" fill="currentColor" />
      </svg>
      Why?
    </button>
  )
}

function ConfidenceBar({ value }: { value: number }) {
  const tone = value >= 85 ? 'bg-success' : value >= 60 ? 'bg-warning' : 'bg-muted'
  return (
    <div className="flex items-center gap-2">
      <div
        className="h-1.5 w-24 overflow-hidden rounded-full bg-line"
        role="meter"
        aria-valuenow={value}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-label="Confidence"
      >
        <div className={`h-full rounded-full ${tone}`} style={{ width: `${value}%` }} />
      </div>
      <span className="tnum text-xs font-semibold text-ink">{value}%</span>
    </div>
  )
}

export function AIInsightCard({
  txn,
  diagnosis,
  loading,
  fromCache,
  aiError,
  onExplain,
  onAnalyze,
  canAnalyze,
}: {
  txn: TracedTransaction
  diagnosis: Diagnosis | null
  loading: boolean
  fromCache: boolean
  aiError: string | null
  onExplain: (req: EvidenceRequest) => void
  onAnalyze: () => void
  canAnalyze: boolean
}) {
  return (
    <section className="rounded-lg border border-ai-line bg-ai-bg shadow-card" aria-labelledby="ai-insight-title">
      <div className="flex items-center justify-between gap-3 border-b border-ai-line px-4 py-3">
        <div className="flex items-center gap-2">
          <svg className="h-4 w-4 text-ai" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path
              d="M12 3l1.9 4.6L18.5 9.5l-4.6 1.9L12 16l-1.9-4.6L5.5 9.5l4.6-1.9L12 3z"
              stroke="currentColor"
              strokeWidth="1.8"
              strokeLinejoin="round"
            />
            <path d="M18 15.5l.9 2.1 2.1.9-2.1.9-.9 2.1-.9-2.1-2.1-.9 2.1-.9.9-2.1z" fill="currentColor" />
          </svg>
          <h2 id="ai-insight-title" className="text-[13px] font-semibold uppercase tracking-wider text-ai-head">
            AI insight
          </h2>
        </div>
        <div className="flex items-center gap-2">
          {diagnosis && (
            <span
              className="chip border-ai-line bg-surface/70 text-ai"
              title={
                diagnosis.source === 'ai'
                  ? 'Generated by the model from this transaction’s records'
                  : 'Generated by the built-in rules engine, with no API call'
              }
            >
              {diagnosis.source === 'ai' ? 'Model analysis' : 'Rule-based'}
            </span>
          )}
          {fromCache && (
            <span className="chip border-ai-line bg-surface/70 text-ink-2" title="Served from cache — no API call was made">
              Cached
            </span>
          )}
        </div>
      </div>

      <div className="px-4 py-4">
        {loading ? (
          <div aria-live="polite" aria-busy="true">
            <p className="text-sm font-medium text-ai-head">Analysing transaction…</p>
            <div className="mt-3 space-y-2">
              <SkeletonLine className="w-4/5" />
              <SkeletonLine className="w-3/5" />
              <SkeletonLine className="w-2/3" />
            </div>
          </div>
        ) : !diagnosis ? (
          <div>
            <p className="text-sm text-ink-2">
              No analysis has been run for this transaction yet.
            </p>
            <button type="button" onClick={onAnalyze} className="btn btn-ai mt-3" disabled={!canAnalyze}>
              Investigate this transaction
            </button>
          </div>
        ) : (
          <div className="fade-rise">
            {/* What happened */}
            <h3 className="text-[11px] font-semibold uppercase tracking-wider text-ink-2">What happened</h3>
            <p className="mt-1 text-sm leading-relaxed text-ink">{diagnosis.headline}</p>

            {/* Likely cause, or the honest "cannot determine" branch */}
            {diagnosis.likelyCause ? (
              <div className="mt-4">
                <h3 className="text-[11px] font-semibold uppercase tracking-wider text-ink-2">Likely cause</h3>
                <p className="mt-1 text-[15px] font-semibold leading-snug text-ink">
                  {diagnosis.likelyCause.text}{' '}
                  <WhyButton
                    onClick={() =>
                      onExplain({ claim: diagnosis.likelyCause as CausalClaim, kind: 'Likely cause' })
                    }
                    label={`Show evidence for: ${diagnosis.likelyCause.text}`}
                  />
                </p>
                <div className="mt-2">
                  <ConfidenceBar value={diagnosis.likelyCause.confidence} />
                </div>
              </div>
            ) : (
              <div className="mt-4 rounded-md border border-warning/40 bg-warning/5 p-3">
                <p className="text-sm font-semibold text-ink">I couldn’t determine the exact cause.</p>
                {diagnosis.alternatives.length > 0 && (
                  <>
                    <p className="mt-1 text-xs text-ink-2">
                      Based on the available records, there {diagnosis.alternatives.length === 1 ? 'is' : 'are'}{' '}
                      {diagnosis.alternatives.length} possible{' '}
                      {diagnosis.alternatives.length === 1 ? 'explanation' : 'explanations'}:
                    </p>
                    <ul className="mt-2.5 space-y-2">
                      {diagnosis.alternatives.map((alt, i) => (
                        <li key={i} className="flex items-start gap-2.5">
                          <span className="tnum mt-px w-9 shrink-0 text-right text-xs font-semibold text-ink">
                            {alt.confidence}%
                          </span>
                          <span className="text-xs leading-snug text-ink-2">
                            {alt.text}{' '}
                            {alt.evidenceIds.length > 0 && (
                              <WhyButton
                                onClick={() => onExplain({ claim: alt, kind: 'Possible explanation' })}
                                label={`Show evidence for: ${alt.text}`}
                              />
                            )}
                          </span>
                        </li>
                      ))}
                    </ul>
                  </>
                )}
                <p className="mt-2.5 text-xs text-muted">
                  {diagnosis.definitiveFailureCode
                    ? `Reported code: ${diagnosis.definitiveFailureCode}`
                    : 'No definitive failure code was found in any log.'}
                </p>
              </div>
            )}

            {/* Evidence summary, derived from the trace rather than the model */}
            <div className="mt-4 border-t border-ai-line pt-3">
              <h3 className="text-[11px] font-semibold uppercase tracking-wider text-ink-2">Evidence</h3>
              <ul className="mt-1.5 space-y-1">
                {txn.evidence
                  // One line per meaningful fact keeps this scannable at a glance.
                  .filter((e) => e.kind === 'absence' || e.tone !== 'ok' || e.event !== 'HANDOFF_TO_BANK')
                  .map((e) => (
                    <li key={e.id} className="flex items-start gap-2 text-xs text-ink-2">
                      <ToneGlyph tone={e.tone} />
                      <span className="leading-snug">{e.label}</span>
                    </li>
                  ))}
              </ul>
            </div>

            {diagnosis.definitiveFailureCode && diagnosis.likelyCause && (
              <p className="mt-3 text-xs text-ink-2">
                Reported failure code:{' '}
                <span className="font-mono font-semibold text-warning">{diagnosis.definitiveFailureCode}</span>
              </p>
            )}

            {aiError && (
              <p className="mt-3 rounded-md border border-line bg-surface px-2.5 py-2 text-xs text-ink-2">
                <span className="font-semibold text-ink">Model unavailable.</span> {aiError} Showing the
                built-in rule-based diagnosis instead.
              </p>
            )}
          </div>
        )}
      </div>
    </section>
  )
}
