"""Typed data model for the SettleSherlock Investigation AI agent.

Everything the agent produces flows through these structures so that the
report shape is stable and machine-consumable by the backend API.

A central concern of this module is *provenance*: every conclusion carries a
:class:`Provenance` marker so a human reviewer can always tell whether a
statement was calculated deterministically from the evidence or generated by
a language model.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Iterable, Mapping, Sequence

__all__ = [
    "Severity",
    "Importance",
    "Provenance",
    "EvidenceGrade",
    "TransactionStatus",
    "ValidationIssue",
    "Transaction",
    "DataQuality",
    "DetectedPattern",
    "EvidenceItem",
    "TimelineEvent",
    "Entity",
    "Hypothesis",
    "InvestigationReport",
    "severity_rank",
    "max_severity",
    "importance_for_severity",
]


# --------------------------------------------------------------------------- #
# Enumerations
# --------------------------------------------------------------------------- #
class Severity(str, Enum):
    """Case / pattern severity, ordered by :func:`severity_rank`."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Importance(str, Enum):
    """How much weight a single piece of evidence carries."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Provenance(str, Enum):
    """Where a statement came from.

    ``DETERMINISTIC`` values are computed by the analysis code in this package
    and are reproducible. ``LLM`` values are generated by a language model and
    must be treated as interpretation, never as fact.
    """

    DETERMINISTIC = "deterministic"
    LLM = "llm"


class EvidenceGrade(str, Enum):
    """Epistemic status of a claim, as required by the root-cause stage."""

    CONFIRMED_FACT = "confirmed_fact"
    STRONG_EVIDENCE = "strong_evidence"
    HYPOTHESIS = "hypothesis"
    UNKNOWN = "unknown"


class TransactionStatus(str, Enum):
    """Canonical transaction states after normalization."""

    SUCCESS = "success"
    FAILED = "failed"
    PENDING = "pending"
    REVERSED = "reversed"
    REFUNDED = "refunded"
    CANCELLED = "cancelled"
    UNKNOWN = "unknown"


_SEVERITY_ORDER: dict[Severity, int] = {
    Severity.LOW: 0,
    Severity.MEDIUM: 1,
    Severity.HIGH: 2,
    Severity.CRITICAL: 3,
}


def severity_rank(severity: Severity) -> int:
    """Return a sortable integer rank for ``severity`` (low=0 … critical=3)."""
    return _SEVERITY_ORDER[severity]


def max_severity(severities: Iterable[Severity], default: Severity = Severity.LOW) -> Severity:
    """Return the highest severity in ``severities``, or ``default`` if empty."""
    ranked = sorted(severities, key=severity_rank, reverse=True)
    return ranked[0] if ranked else default


def importance_for_severity(severity: Severity) -> Importance:
    """Map a pattern severity onto the importance of its evidence items."""
    if severity in (Severity.CRITICAL, Severity.HIGH):
        return Importance.HIGH
    if severity is Severity.MEDIUM:
        return Importance.MEDIUM
    return Importance.LOW


# --------------------------------------------------------------------------- #
# Serialization helpers
# --------------------------------------------------------------------------- #
def _plain(value: Any) -> Any:
    """Recursively convert domain objects into JSON-safe primitives."""
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, Decimal):
        # Money is kept as Decimal internally; expose it as a float for JSON.
        return float(value)
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, Mapping):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set, frozenset)):
        return [_plain(v) for v in value]
    if hasattr(value, "to_dict"):
        return value.to_dict()
    return str(value)


# --------------------------------------------------------------------------- #
# Input side
# --------------------------------------------------------------------------- #
@dataclass(slots=True)
class ValidationIssue:
    """A single problem found while ingesting a raw evidence record."""

    record_index: int
    field: str
    problem: str
    severity: Severity = Severity.LOW
    transaction_id: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "record_index": self.record_index,
            "field": self.field,
            "problem": self.problem,
            "severity": self.severity.value,
            "transaction_id": self.transaction_id,
        }


@dataclass(slots=True)
class Transaction:
    """A normalized transaction record.

    Every field except ``index``/``transaction_id`` is optional: real-world
    evidence arrives incomplete and the agent must degrade gracefully rather
    than reject the case.
    """

    index: int
    transaction_id: str
    timestamp: datetime | None = None
    sender: str | None = None
    receiver: str | None = None
    amount: Decimal | None = None
    currency: str | None = None
    transaction_type: str | None = None
    account_id: str | None = None
    bank: str | None = None
    gateway: str | None = None
    status: TransactionStatus = TransactionStatus.UNKNOWN
    raw_status: str | None = None
    reference_id: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    raw: dict[str, Any] = field(default_factory=dict)
    issues: list[ValidationIssue] = field(default_factory=list)
    synthetic_id: bool = False

    # -- convenience accessors ------------------------------------------- #
    @property
    def counterparty_key(self) -> tuple[str, str]:
        """A stable ``(sender, receiver)`` key, tolerant of missing values."""
        return (self.sender or "<unknown-sender>", self.receiver or "<unknown-receiver>")

    @property
    def is_terminal_failure(self) -> bool:
        return self.status in (TransactionStatus.FAILED, TransactionStatus.CANCELLED)

    @property
    def is_value_moving(self) -> bool:
        """True when the record represents money that actually moved."""
        return self.status in (TransactionStatus.SUCCESS, TransactionStatus.PENDING)

    def to_dict(self) -> dict[str, Any]:
        return {
            "transaction_id": self.transaction_id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "sender": self.sender,
            "receiver": self.receiver,
            "amount": _plain(self.amount),
            "currency": self.currency,
            "transaction_type": self.transaction_type,
            "account_id": self.account_id,
            "bank": self.bank,
            "gateway": self.gateway,
            "status": self.status.value,
            "reference_id": self.reference_id,
            "metadata": _plain(self.metadata),
        }


@dataclass(slots=True)
class DataQuality:
    """Summary of how trustworthy the submitted evidence is."""

    records_submitted: int
    records_parsed: int
    records_rejected: int
    field_completeness: float
    missing_fields: dict[str, int] = field(default_factory=dict)
    issues: list[ValidationIssue] = field(default_factory=list)
    conflicting_record_count: int = 0

    @property
    def rejection_ratio(self) -> float:
        if self.records_submitted == 0:
            return 0.0
        return self.records_rejected / self.records_submitted

    def to_dict(self) -> dict[str, Any]:
        return {
            "records_submitted": self.records_submitted,
            "records_parsed": self.records_parsed,
            "records_rejected": self.records_rejected,
            "field_completeness": round(self.field_completeness, 3),
            "conflicting_record_count": self.conflicting_record_count,
            "missing_fields": dict(sorted(self.missing_fields.items())),
            "issues": [i.to_dict() for i in self.issues],
        }


# --------------------------------------------------------------------------- #
# Output side
# --------------------------------------------------------------------------- #
@dataclass(slots=True)
class DetectedPattern:
    """A behavioural pattern found by a deterministic detector."""

    pattern_id: str
    name: str
    description: str
    severity: Severity
    confidence: float
    transaction_ids: list[str] = field(default_factory=list)
    entities: list[str] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)
    grade: EvidenceGrade = EvidenceGrade.STRONG_EVIDENCE
    provenance: Provenance = Provenance.DETERMINISTIC

    def to_dict(self) -> dict[str, Any]:
        return {
            "pattern_id": self.pattern_id,
            "name": self.name,
            "description": self.description,
            "severity": self.severity.value,
            "confidence": round(self.confidence, 3),
            "transaction_ids": list(self.transaction_ids),
            "entities": list(self.entities),
            "metrics": _plain(self.metrics),
            "grade": self.grade.value,
            "provenance": self.provenance.value,
        }


@dataclass(slots=True)
class EvidenceItem:
    """Links one finding back to the record that supports it."""

    transaction_id: str | None
    finding: str
    importance: Importance
    pattern_id: str | None = None
    grade: EvidenceGrade = EvidenceGrade.STRONG_EVIDENCE
    provenance: Provenance = Provenance.DETERMINISTIC

    def to_dict(self) -> dict[str, Any]:
        return {
            "transaction_id": self.transaction_id,
            "finding": self.finding,
            "importance": self.importance.value,
            "pattern_id": self.pattern_id,
            "grade": self.grade.value,
            "provenance": self.provenance.value,
        }


@dataclass(slots=True)
class TimelineEvent:
    """One entry in the reconstructed chronology."""

    timestamp: datetime | None
    event: str
    importance: Importance
    transaction_id: str | None = None
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "transaction_id": self.transaction_id,
            "event": self.event,
            "importance": self.importance.value,
            "details": _plain(self.details),
        }


@dataclass(slots=True)
class Entity:
    """An account, user, bank, gateway or merchant touched by the case."""

    entity_id: str
    entity_type: str
    roles: list[str] = field(default_factory=list)
    transaction_count: int = 0
    outbound_count: int = 0
    inbound_count: int = 0
    total_amount: Decimal | None = None
    currencies: list[str] = field(default_factory=list)
    linked_entities: list[str] = field(default_factory=list)
    flags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "entity_id": self.entity_id,
            "entity_type": self.entity_type,
            "roles": sorted(self.roles),
            "transaction_count": self.transaction_count,
            "outbound_count": self.outbound_count,
            "inbound_count": self.inbound_count,
            "total_amount": _plain(self.total_amount),
            "currencies": sorted(self.currencies),
            "linked_entities": sorted(self.linked_entities),
            "flags": sorted(set(self.flags)),
        }


@dataclass(slots=True)
class Hypothesis:
    """A candidate explanation for the observed evidence."""

    conclusion: str
    confidence: float
    reasoning: list[str] = field(default_factory=list)
    supporting_pattern_ids: list[str] = field(default_factory=list)
    supporting_transaction_ids: list[str] = field(default_factory=list)
    contradicting_observations: list[str] = field(default_factory=list)
    grade: EvidenceGrade = EvidenceGrade.HYPOTHESIS
    provenance: Provenance = Provenance.DETERMINISTIC

    def to_dict(self) -> dict[str, Any]:
        return {
            "conclusion": self.conclusion,
            "confidence": round(self.confidence, 3),
            "reasoning": list(self.reasoning),
            "supporting_pattern_ids": list(self.supporting_pattern_ids),
            "supporting_transaction_ids": list(self.supporting_transaction_ids),
            "contradicting_observations": list(self.contradicting_observations),
            "grade": self.grade.value,
            "provenance": self.provenance.value,
        }


@dataclass(slots=True)
class InvestigationReport:
    """The complete structured output of an investigation."""

    case_summary: str
    severity: Severity
    suspicious_transactions: list[dict[str, Any]] = field(default_factory=list)
    entities_involved: list[Entity] = field(default_factory=list)
    timeline: list[TimelineEvent] = field(default_factory=list)
    detected_patterns: list[DetectedPattern] = field(default_factory=list)
    root_cause: Hypothesis | None = None
    evidence: list[EvidenceItem] = field(default_factory=list)
    alternative_hypotheses: list[Hypothesis] = field(default_factory=list)
    unknowns: list[str] = field(default_factory=list)
    recommended_next_steps: list[str] = field(default_factory=list)
    confirmed_facts: list[str] = field(default_factory=list)
    statistics: dict[str, Any] = field(default_factory=dict)
    data_quality: DataQuality | None = None
    case_summary_source: Provenance = Provenance.DETERMINISTIC
    ai_narrative: dict[str, Any] | None = None
    meta: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Render the report as the JSON contract consumed by the backend."""
        return {
            "case_summary": self.case_summary,
            "case_summary_source": self.case_summary_source.value,
            "severity": self.severity.value,
            "suspicious_transactions": _plain(self.suspicious_transactions),
            "entities_involved": [e.to_dict() for e in self.entities_involved],
            "timeline": [t.to_dict() for t in self.timeline],
            "detected_patterns": [p.to_dict() for p in self.detected_patterns],
            "root_cause": self.root_cause.to_dict() if self.root_cause else None,
            "evidence": [e.to_dict() for e in self.evidence],
            "alternative_hypotheses": [h.to_dict() for h in self.alternative_hypotheses],
            "unknowns": list(self.unknowns),
            "recommended_next_steps": list(self.recommended_next_steps),
            "confirmed_facts": list(self.confirmed_facts),
            "statistics": _plain(self.statistics),
            "data_quality": self.data_quality.to_dict() if self.data_quality else None,
            "ai_narrative": _plain(self.ai_narrative),
            "meta": _plain(self.meta),
        }

    def to_json(self, indent: int | None = 2) -> str:
        """Serialize the report to a JSON string."""
        return json.dumps(self.to_dict(), indent=indent, sort_keys=False)

    # -- small helpers used by callers / tests ---------------------------- #
    def pattern_ids(self) -> list[str]:
        return [p.pattern_id for p in self.detected_patterns]

    def has_pattern(self, pattern_id: str) -> bool:
        return any(p.pattern_id == pattern_id for p in self.detected_patterns)

    def suspicious_transaction_ids(self) -> list[str]:
        return [str(t.get("transaction_id")) for t in self.suspicious_transactions]


def as_report_list(items: Sequence[Any]) -> list[dict[str, Any]]:
    """Convert a sequence of domain objects into plain dicts (test helper)."""
    return [_plain(i) for i in items]
